## Data Overview Libraries ##

This cell loads the basic libraries used to read and inspect your dataset.
1 pandas for loading and viewing CSV files

2  numpy for numerical support

3 matplotlib and seaborn for simple visualizations

4 Display settings help show all columns clearly in VS Code

Use these libraries only for understanding your data before cleaning or modelling.

In [2]:
# Data overview libraries
import pandas as pd      # Load and view CSV data
import numpy as np       # Numerical operations (optional but useful)

# Visualization (optional but helpful for understanding data)
import matplotlib.pyplot as plt
import seaborn as sns

# Make pandas display wider in VS Code
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1200)

print("✅ Libraries for data overview loaded successfully!")

✅ Libraries for data overview loaded successfully!

## 📂 Data Loading  
This cell locates the project root by searching for the `data` directory and then loads all raw CSV files from `data/raw`.  
Each file is imported into a dedicated DataFrame (`df_cpi`, `df_interest`, `df_exchange`, `df_gdp`, `df_unemp`, `df_oil`) for subsequent cleaning, merging, and analysis.

In [3]:
# ============================================
# 📂 Load all raw CSV datasets (collaborative-safe)
# ============================================

import os
import pandas as pd

# 1) Locate project root by searching for "data" folder
BASE_DIR = os.getcwd()
while "data" not in os.listdir(BASE_DIR) and os.path.dirname(BASE_DIR) != BASE_DIR:
    BASE_DIR = os.path.dirname(BASE_DIR)

RAW_DIR = os.path.join(BASE_DIR, "data", "raw")

print("Project root:", BASE_DIR)
print("Raw data folder:", RAW_DIR)
print("Files in raw:", os.listdir(RAW_DIR))
print("=====================================\n")

# 2) Load each dataset into a named DataFrame

df_cpi = pd.read_csv(os.path.join(RAW_DIR, "ons_cpi.csv"), low_memory=False)
df_interest = pd.read_csv(os.path.join(RAW_DIR, "boe_interest.csv"))
df_exchange = pd.read_csv(os.path.join(RAW_DIR, "exchange_rates.csv"))
df_gdp = pd.read_csv(os.path.join(RAW_DIR, "GDP_growth_Rate.csv"))
df_unemp = pd.read_csv(os.path.join(RAW_DIR, "Unemployment_Rate.csv"))
df_oil = pd.read_csv(os.path.join(RAW_DIR, "petrol_oil_everage_price_change.csv"))

print("Loaded DataFrames:")
print("  df_cpi      -> ons_cpi.csv")
print("  df_interest -> boe_interest.csv")
print("  df_exchange -> exchange_rates.csv")
print("  df_gdp      -> GDP_growth_Rate.csv")
print("  df_unemp    -> Unemployment_Rate.csv")
print("  df_oil      -> petrol_oil_everage_price_change.csv")

Project root: c:\Users\reset\OneDrive - UWE Bristol\Master_project\UK-inflation-forecasting-XAI
Raw data folder: c:\Users\reset\OneDrive - UWE Bristol\Master_project\UK-inflation-forecasting-XAI\data\raw
Files in raw: ['.Rhistory', 'boe_interest.csv', 'exchange_rates.csv', 'GDP_growth_Rate.csv', 'ons_cpi.csv', 'petrol_oil_everage_price_change.csv', 'Unemployment_Rate.csv']
=====================================

Loaded DataFrames:
  df_cpi      -> ons_cpi.csv
  df_interest -> boe_interest.csv
  df_exchange -> exchange_rates.csv
  df_gdp      -> GDP_growth_Rate.csv
  df_unemp    -> Unemployment_Rate.csv
  df_oil      -> petrol_oil_everage_price_change.csv

## 📊 CPI Dataset Overview  
This cell reports the total number of rows and columns, displays the first ten records, and prints the complete list of column names in a column-wise format to support variable inspection and selection.

In [3]:

# 📊 CPI Data Overview (rows, columns, head, col list)

# Total rows and columns
print("Total rows:", df_cpi.shape[0])
print("Total columns:", df_cpi.shape[1])
print("=====================================\n")

# First 10 rows
print("First 10 rows:")
display(df_cpi.head(10))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_cpi.columns:
    print("-", col)

Total rows: 1481
Total columns: 4054
=====================================

First 10 rows:

             Title CPI wts: Non-energy industrial goods GOODS CPI wts: Durables GOODS CPI wts: Semi-durables GOODS CPI wts: Non-durables GOODS CPI wts: Non-seasonal food GOODS CPI wts: Food, alcoholic beverages & tobacco GOODS CPI wts: Processed food & non-alcoholic beverages GOODS CPI wts: Unprocessed food GOODS CPI wts: Seasonal food GOODS CPI wts: Industrial goods GOODS CPI wts: Energy GOODS CPI wts: Electricity, gas & misc. energy GOODS CPI wts: CPI excluding tobacco SPECIAL AGGREGATES CPI wts: Clothing & footwear goods GOODS CPI wts: Housing goods GOODS CPI wts: Household goods GOODS CPI wts: Water supply; materials for maintenance & repair GOODS CPI wts: Medical goods GOODS CPI wts: Vehicles, spare parts & accessories GOODS CPI wts: Recreational goods GOODS CPI wts: Audio-visual goods GOODS CPI wts: Other recreational goods GOODS CPI wts: Miscellaneous goods GOODS CPI wts: Housing services SERVICES CPI wts: Primary housing services SERVICES CPI wts: Other housing services SERVICES CPI wts: Travel & transport services SERVICES CPI wts: Services for personal transport equipment SERVICES CPI wts: Recreational & personal services SERVICES  \
0             CDID                                       A9ER                    A9ES                         A9ET                        A9EU                             A9EV                                               A9EW                                               A9EX                                 A9EY                         A9EZ                            A9F2                  A9F3                                           A9F4                                              A9F5                                     A9F6                         A9F7                           A9F8                                               A9F9                                      A9FA                                               A9FB                              A9FC                              A9FD                                    A9FE                               A9FF                               A9FG                                       A9FH                                     A9FI                                          A9FJ                                               A9FK                                                        A9FL
1          PreUnit                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN
2             Unit                             Parts per 1000          Parts per 1000               Parts per 1000              Parts per 1000                   Parts per 1000                                     Parts per 1000                                     Parts per 1000                       Parts per 1000               Parts per 1000                  Parts per 1000        Parts per 1000                                 Parts per 1000                                    Parts per 1000                           Parts per 1000               Parts per 1000                 Parts per 1000                                     Parts per 1000                            Parts per 1000                                     Parts per 1000                    Parts per 1000                    Parts per 1000                          Parts per 1000                     Parts per 1000                     Parts per 1000                             Parts per 1000                           Parts per 1000                                Parts per 1000                                     Parts per 1000                                              Parts per 1000
3     Release Date                                 22-10-2025              22-10-2025                   22-10-2025                  22-10-2025                       22-10-2025                                         22-10-2025                                         22-10-2025                           22-10-2025                   22-10-2025                      22-10-2025            22-10-2025                                     22-10-2025                                        22-10-2025                               22-10-2025                   22-10-2025                     22-10-2025                                         22-10-2025                                22-10-2025                                         22-10-2025                        22-10-2025                        22-10-2025                              22-10-2025                         22-10-2025                         22-10-2025                                 22-10-2025                               22-10-2025                                    22-10-2025                                         22-10-2025                                                  22-10-2025
4     Next release                           19 November 2025        19 November 2025             19 November 2025            19 November 2025                 19 November 2025                                   19 November 2025                                   19 November 2025                     19 November 2025             19 November 2025                19 November 2025      19 November 2025                               19 November 2025                                  19 November 2025                         19 November 2025             19 November 2025               19 November 2025                                   19 November 2025                          19 November 2025                                   19 November 2025                  19 November 2025                  19 November 2025                        19 November 2025                   19 November 2025                   19 November 2025                           19 November 2025                         19 November 2025                              19 November 2025                                   19 November 2025                                            19 November 2025
5  Important Notes                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN
6             1800                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN
7             1801                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN
8             1802                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN
9             1803                                        NaN                     NaN                          NaN                         NaN                              NaN                                                NaN                                                NaN                                  NaN                          NaN                             NaN                   NaN                                            NaN                                               NaN                                      NaN                          NaN                            NaN                                                NaN                                       NaN                                                NaN                               NaN                               NaN                                     NaN                                NaN                                NaN                                        NaN                                      NaN                                           NaN                                                NaN                                                         NaN

  CPI wts: Package holidays & accommodation SERVICES CPI wts: Other recreational & personal services SERVICES CPI wts: Non-catering recreational & personal services SERVICES CPI wts: Miscellaneous services SERVICES CPI wts: Miscellaneous & other services SERVICES CPI wts: Medical services (dec 1999=100) SERVICES CPI wts: Liquid fuels, vehicle fuels & lubricants GOODS CPI wts: CPI excluding energy SPECIAL AGGREGATES CPI wts: CPI excluding energy, food, alcohol & tobacco SPECIAL AGGREGATES CPI wts: CPI excluding energy & unprocessed food SPECIAL AGGREGATES CPI wts: CPI excluding seasonal food SPECIAL AGGREGATES CPI wts: CPI excluding energy & seasonal food SPECIAL AGGREGATES CPI wts: CPI excluding alcohol & tobacco SPECIAL AGGREGATES CPI wts: CPI ex. liquid fuels, vehicle fuels & lubricants SPECIAL AGGREGATES CPI wts: CPI ex. housing, water, elec., gas & other fuels SPECIAL AGGREGATES CPI wts: CPI ex. education, health & social protection SPECIAL AGGREGATES CPI wts: Energy, food, alcohol and tobacco SPECIAL AGGREGATES CPI wts: Energy and unprocessed food SPECIAL AGGREGATES CPI wts: Energy and seasonal food SPECIAL AGGREGATES  \
0                                               A9FM                                               A9FN                                                     A9FO                                                  A9FP                                             A9FQ                                              A9FR                                               A9FS                                                  A9FT                                               A9FU                                                                      A9FV                                                                A9FW                                                    A9FX                                                             A9FY                                                        A9FZ                                                                         A9G2                                                                         A9G3                                                                      A9G4                                                          A9G5                                                    A9G6
1                                                NaN                                                NaN                                                      NaN                                                   NaN                                              NaN                                               NaN                                                NaN                                                   NaN                                                NaN                                                                       NaN                                                                 NaN                                                     NaN                                                              NaN                                                         NaN                                                                          NaN                                                                          NaN                                                                       NaN                                                           NaN                                                     NaN
2                                     Parts per 1000                                     Parts per 1000                                           Parts per 1000                                        Parts per 1000                                   Parts per 1000                                    Parts per 1000                                     Parts per 1000                                        Parts per 1000                                     Parts per 1000                                                            Parts per 1000                                                      Parts per 1000                                          Parts per 1000                                                   Parts per 1000                                              Parts per 1000                                                               Parts per 1000                                                               Parts per 1000                                                            Parts per 1000                                                Parts per 1000                                          Parts per 1000
3                                         22-10-2025                                         22-10-2025                                               22-10-2025                                            22-10-2025                                       22-10-2025                                        22-10-2025                                         22-10-2025                                            22-10-2025                                         22-10-2025                                                                22-10-2025                                                          22-10-2025                                              22-10-2025                                                       22-10-2025                                                  22-10-2025                                                                   22-10-2025                                                                   22-10-2025                                                                22-10-2025                                                    22-10-2025                                              22-10-2025
4                                   19 November 2025                                   19 November 2025                                         19 November 2025                                      19 November 2025                                 19 November 2025                                  19 November 2025                                   19 November 2025                                      19 November 2025                                   19 November 2025                                                          19 November 2025                                                    19 November 2025                                        19 November 2025                                                 19 November 2025                                            19 November 2025                                                             19 November 2025                                                             19 November 2025                                                          19 November 2025                                              19 November 2025                                        19 November 2025

=====================================

Column names:
- Title
- CPI wts: Non-energy industrial goods GOODS
- CPI wts: Durables GOODS
- CPI wts: Semi-durables GOODS
- CPI wts: Non-durables GOODS
- CPI wts: Non-seasonal food GOODS
- CPI wts: Food, alcoholic beverages & tobacco GOODS
- CPI wts: Processed food & non-alcoholic beverages GOODS
- CPI wts: Unprocessed food GOODS
- CPI wts: Seasonal food GOODS
- CPI wts: Industrial goods GOODS
- CPI wts: Energy GOODS
- CPI wts: Electricity, gas & misc. energy GOODS
- CPI wts: CPI excluding tobacco SPECIAL AGGREGATES
- CPI wts: Clothing & footwear goods GOODS
- CPI wts: Housing goods GOODS
- CPI wts: Household goods GOODS
- CPI wts: Water supply; materials for maintenance & repair GOODS
- CPI wts: Medical goods GOODS
- CPI wts: Vehicles, spare parts & accessories GOODS
- CPI wts: Recreational goods GOODS
- CPI wts: Audio-visual goods GOODS
- CPI wts: Other recreational goods GOODS
- CPI wts: Miscellaneous goods GOODS
- CPI wts: Housing services SERVICES
- CPI wts: Primary housing services SERVICES
- CPI wts: Other housing services SERVICES
- CPI wts: Travel & transport services SERVICES
- CPI wts: Services for personal transport equipment SERVICES
- CPI wts: Recreational & personal services SERVICES
- CPI wts: Package holidays & accommodation SERVICES
- CPI wts: Other recreational & personal services SERVICES
- CPI wts: Non-catering recreational & personal services SERVICES
- CPI wts: Miscellaneous services SERVICES
- CPI wts: Miscellaneous & other services SERVICES
- CPI wts: Medical services (dec 1999=100) SERVICES
- CPI wts: Liquid fuels, vehicle fuels & lubricants GOODS
- CPI wts: CPI excluding energy SPECIAL AGGREGATES
- CPI wts: CPI excluding energy, food, alcohol & tobacco SPECIAL AGGREGATES
- CPI wts: CPI excluding energy & unprocessed food SPECIAL AGGREGATES
- CPI wts: CPI excluding seasonal food SPECIAL AGGREGATES
- CPI wts: CPI excluding energy & seasonal food SPECIAL AGGREGATES
- CPI wts: CPI excluding alcohol & tobacco SPECIAL AGGREGATES
- CPI wts: CPI ex. liquid fuels, vehicle fuels & lubricants SPECIAL AGGREGATES
- CPI wts: CPI ex. housing, water, elec., gas & other fuels SPECIAL AGGREGATES
- CPI wts: CPI ex. education, health & social protection SPECIAL AGGREGATES
- CPI wts: Energy, food, alcohol and tobacco SPECIAL AGGREGATES
- CPI wts: Energy and unprocessed food SPECIAL AGGREGATES
- CPI wts: Energy and seasonal food SPECIAL AGGREGATES
- CPI wts: Education, health and social protection SPECIAL AGGREGATES
- Internal purchasing power of the pound (based on RPI): 1977=100
- Internal purchasing power of the pound (based on RPI): 1978=100
- Internal purchasing power of the pound (based on RPI): 1979=100
- Internal purchasing power of the pound (based on RPI): 1980=100
- Internal purchasing power of the pound (based on RPI): 1981=100
- Internal purchasing power of the pound (based on RPI): 1982=100
- Internal purchasing power of the pound (based on RPI): 1983=100
- Internal purchasing power of the pound (based on RPI): 1984=100
- Internal purchasing power of the pound (based on RPI): 1985=100
- Internal purchasing power of the pound (based on RPI): 1986=100
- Internal purchasing power of the pound (based on RPI): 1987=100
- Internal purchasing power of the pound (based on RPI): 1988=100
- Internal purchasing power of the pound (based on RPI): 1989=100
- Internal purchasing power of the pound (based on RPI): 1990=100
- Internal purchasing power of the pound (based on RPI): 1991=100
- Internal purchasing power of the pound (based on RPI): 2004=100
- RPI:Percentage change over 12 months - Milk fresh
- RPI:Percentage change over 12 months - Milk products
- RPI:Percentage change over 12 months - Tea
- RPI:Percentage change over 12 months - Coffee and other hot drinks
- RPI:Weights (parts per 1000) One-person pensioner - Take-aways and snacks
- RPI:Weights (parts per 1000) One-person pensioner - Beer on sales
- RPI:Weights (parts per 1000) One-person pensioner - Beer off sales
- RPI:Weights (parts per 1000) One-person pensioner - Wines & spirits on sales
- RPI:Weights (parts per 1000) One-person pensioner - Wines & spirits off sales
- RPI:Weights (parts per 1000) One-person pensioner - Cigarettes
- RPI:Weights (parts per 1000) One-person pensioner - Other Tobacco
- RPI:Weights (parts per 1000) - Food and Catering
- RPI:Weights (parts per 1000) - Alcohol and Tobacco
- RPI:Weights (parts per 1000) - Housing and Household Expenditure
- RPI:Weights (parts per 1000) - Personal Expenditure
- RPI:Weights (parts per 1000) - Travel and Leisure
- RPI:Weights (parts per 1000) - Consumer Durables
- RPI:Weights (parts per 1000) One-person pensioner - Foreign holidays
- RPI:Weights (parts per 1000) One-person pensioner - Coal and solid fuels
- RPI:Weights (parts per 1000) One-person pensioner - Electricity
- RPI:Weights (parts per 1000) One-person pensioner - Gas
- RPI:Weights (parts per 1000) One-person pensioner - Oil and other fuels
- RPI:Weights (parts per 1000) One-person pensioner - Furniture
- RPI:Weights (parts per 1000) One-person pensioner - Furnishings
- RPI:Weights (parts per 1000) One-person pensioner - Electrical appliances
- RPI:Weights (parts per 1000) One-person pensioner - Other household equipment
- RPI:Weights (parts per 1000) One-person pensioner - Household consumables
- RPI:Weights (parts per 1000) One-person pensioner - Pet care
- RPI:Weights (parts per 1000) One-person pensioner - Postage
- RPI:Weights (parts per 1000) One-person pensioner - Telephones, telemessages, et
- RPI:Weights (parts per 1000) One-person pensioner - Domestic services
- RPI:Weights (parts per 1000) One-person pensioner - Fees and subscriptions
- RPI:Weights (parts per 1000) One-person pensioner - Men's outerwear
- RPI:Weights (parts per 1000) One-person pensioner - Women's outerwear
- RPI:Weights (parts per 1000) One-person pensioner - Children's outerwear
- RPI:Weights (parts per 1000) One-person pensioner - Other clothing
- RPI:Weights (parts per 1000) One-person pensioner - Footwear
- RPI:Weights (parts per 1000) One-person pensioner - Personal articles
- RPI:Weights (parts per 1000) One-person pensioner - Chemists goods
- RPI:Weights (parts per 1000) One-person pensioner - Personal services
- RPI:Weights (parts per 1000) One-person pensioner - Purchase of motor vehicles
- RPI:Weights (parts per 1000) One-person pensioner - Maintenance of motor vehicle
- RPI:Weights (parts per 1000) One-person pensioner - Petrol and oil
- RPI:Weights (parts per 1000) One-person pensioner - Vehicles tax and insurance
- RPI:Weights (parts per 1000) One-person pensioner - Rail fares
- RPI:Weights (parts per 1000) One-person pensioner - Bus and coach fares
- RPI:Weights (parts per 1000) One-person pensioner - Other travel costs
- RPI:Weights (parts per 1000) One-person pensioner - Audio-visual equipment
- RPI:Weights (parts per 1000) One-person pensioner - Records and tapes
- RPI:Weights (parts per 1000) One-person pensioner - Toys, photographic & sports
- RPI:Weights (parts per 1000) One-person pensioner - Books and newspapers
- RPI:Weights (parts per 1000) One-person pensioner - Gardening products
- RPI:Weights (parts per 1000) One-person pensioner - Television licences and rent
- RPI:Weights (parts per 1000) One-person pensioner - Entertainment & other recrea
- RPI:Weights (parts per 1000) Two person pensioner - Foreign holidays
- RPI:Weights (parts per 1000) - Foreign holidays
- RPI:Weights (parts per 1000) One-person pensioner - Food
- RPI:Weights (parts per 1000) One-person pensioner - Catering
- RPI:Weights (parts per 1000) One-person pensioner - Alcoholic drink
- RPI:Weights (parts per 1000) One-person pensioner - Tobacco
- Internal purchasing power of the pound (based on RPI): 1993=100
- RPI:Weights (parts per 1000) One-person pensioner - Fuel and light
- RPI:Weights (parts per 1000) One-person pensioner - Household goods
- RPI:Weights (parts per 1000) One-person pensioner - Household services
- RPI:Weights (parts per 1000) One-person pensioner - Clothing and footwear
- RPI:Weights (parts per 1000) One-person pensioner - Personal goods and services
- RPI:Weights (parts per 1000) One-person pensioner - Motoring expenditure
- RPI:Weights (parts per 1000) One-person pensioner - Fares and other travel costs
- RPI:Weights (parts per 1000) One-person pensioner - Leisure goods
- RPI:Weights (parts per 1000) One-person pensioner - Leisure services
- RPI:Weights (parts per 1000) Two-person pensioner - Bread
- RPI:Weights (parts per 1000) Two-person pensioner - Cereals
- RPI:Weights (parts per 1000) Two-person pensioner - Biscuits and cakes
- RPI:Weights (parts per 1000) Two-person pensioner - Beef
- RPI:Weights (parts per 1000) Two-person pensioner - Home-killed lamb
- RPI:Weights (parts per 1000) Two-person pensioner - imported lamb
- RPI:Weights (parts per 1000) Two-person pensioner - Pork
- RPI:Weights (parts per 1000) Two-person pensioner - Bacon
- RPI:Weights (parts per 1000) Two-person pensioner - Poultry
- RPI:Weights (parts per 1000) Two-person pensioner - Other meat
- RPI:Weights (parts per 1000) Two-person pensioner - Fresh fish
- RPI:Weights (parts per 1000) Two-person pensioner - processed fish
- RPI:Weights (parts per 1000) Two-person pensioner - Butter
- RPI:Weights (parts per 1000) Two-person pensioner - Oils and fats
- RPI:Weights (parts per 1000) Two-person pensioner - Cheese
- RPI:Weights (parts per 1000) Two-person pensioner - Eggs
- RPI:Weights (parts per 1000) Two-person pensioner - Milk, fresh
- RPI:Weights (parts per 1000) Two-person pensioner - Milk products
- RPI:Weights (parts per 1000) Two-person pensioner - Tea
- RPI:Weights (parts per 1000) Two-person pensioner - Coffee and other hot drinks
- RPI:Weights (parts per 1000) Two-person pensioner - Soft drinks
- RPI:Weights (parts per 1000) Two-person pensioner - Sugar and preserves
- RPI:Weights (parts per 1000) Two-person pensioner - Sweets and chocolates
- RPI:Weights (parts per 1000) Two-person pensioner - Unprocessed potatoes
- RPI:Weights (parts per 1000) Two-person pensioner - Processed potatoes
- RPI:Weights (parts per 1000) Two-person pensioner - Fresh vegetables
- RPI:Weights (parts per 1000) Two-person pensioner - Processed vegetables
- RPI:Weights (parts per 1000) Two-person pensioner - Fresh fruit
- RPI:Weights (parts per 1000) Two-person pensioner - Processed fruit
- RPI:Weights (parts per 1000) Two-person pensioner - Other foods
- RPI:Weights (parts per 1000) Two-person pensioner - Restaurant meals
- RPI:Weights (parts per 1000) Two-person pensioner - Canteen meals
- RPI:Weights (parts per 1000) Two-person pensioner - Take-aways and snacks
- RPI:Weights (parts per 1000) Two-person pensioner - beer on sales
- RPI:Weights (parts per 1000) Two-person pensioner - beer off sales
- RPI:Weights (parts per 1000) Two-person pensioner - wines & spirits on sales
- RPI:Weights (parts per 1000) Two-person pensioner - wines & spirits off sales
- RPI:Weights (parts per 1000) Two-person pensioner - Cigarettes
- RPI:Weights (parts per 1000) Two-person pensioner - Other Tobacco
- RPI:All items exc mortgage int payments and indirect taxes (RPIY) (Jan 1987=100)
- RPI:Percentage change over 12 months - All items exc MIPs and indirect taxes
- RPI:Percentage change over 12 months - All items excluding food
- RPI:Percentage change over 12 months - Food
- RPI:Percentage change over 12 months - Bread
- RPI:Percentage change over 12 months - Cereals
- RPI:Weights (parts per 1000) Two-person pensioner - Coal and solid fuels
- RPI:Weights (parts per 1000) Two-person pensioner - Electricity
- RPI:Weights (parts per 1000) Two-person pensioner - Gas
- RPI:Weights (parts per 1000) Two-person pensioner - Oil and other fuels
- RPI:Weights (parts per 1000) Two-person pensioner - Furniture
- RPI:Weights (parts per 1000) Two-person pensioner - Furnishings
- RPI:Weights (parts per 1000) Two-person pensioner - Electrical appliances
- RPI:Weights (parts per 1000) Two-person pensioner - Other household equipment
- RPI:Weights (parts per 1000) Two-person pensioner - Household consumables
- RPI:Weights (parts per 1000) Two-person pensioner - Pet care
- RPI:Weights (parts per 1000) Two-person pensioner - Postage
- RPI:Weights (parts per 1000) Two-person pensioner - Telephones, telemessages, et
- RPI:Weights (parts per 1000) Two-person pensioner - Domestic services
- RPI:Weights (parts per 1000) Two-person pensioner - Fees and subscriptions
- RPI:Weights (parts per 1000) Two-person pensioner - Men's outerwear
- RPI:Weights (parts per 1000) Two-person pensioner - Women's outerwear
- RPI:Weights (parts per 1000) Two-person pensioner - Children's outerwear
- RPI:Weights (parts per 1000) Two-person pensioner - Other clothing
- RPI:Weights (parts per 1000) Two-person pensioner - Footwear
- RPI:Weights (parts per 1000) Two-person pensioner - Personal articles
- RPI:Weights (parts per 1000) Two-person pensioner - Chemists goods
- RPI:Weights (parts per 1000) Two-person pensioner - Personal services
- RPI:Percentage change over 12 months - Biscuits and cakes
- RPI:Percentage change over 12 months - Beef
- RPI:Percentage change over 12 months - Lamb
- RPI:Percentage change over 12 months - home-killed lamb
- RPI:Percentage change over 12 months - Pork
- RPI:Percentage change over 12 months - Bacon
- RPI:Percentage change over 12 months - Poultry
- RPI:Percentage change over 12 months - Other meat
- RPI:Percentage change over 12 months - Fish
- RPI:Percentage change over 12 months - fresh fish
- RPI:Percentage change over 12 months - Butter
- RPI:Percentage change over 12 months - Oils and fats
- RPI:Percentage change over 12 months - Cheese
- RPI:Percentage change over 12 months - Eggs
- RPI:Weights (parts per 1000) Two-person pensioner - Purchase of motor vehicles
- RPI:Weights (parts per 1000) Two-person pensioner - Maintenance of motor vehicle
- RPI:Weights (parts per 1000) Two-person pensioner - Petrol and oil
- RPI:Weights (parts per 1000) Two-person pensioner - Vehicles tax and insurance
- RPI:Weights (parts per 1000) Two-person pensioner - Rail fares
- RPI:Weights (parts per 1000) Two-person pensioner - Bus and coach fares
- RPI:Weights (parts per 1000) Two-person pensioner - Other travel costs
- RPI:Weights (parts per 1000) Two-person pensioner - Audio-visual equipment
- RPI:Weights (parts per 1000) Two-person pensioner - Records and tapes
- RPI:Weights (parts per 1000) Two-person pensioner - Toys, photographic & sports
- RPI:Weights (parts per 1000) Two-person pensioner - Books and newspapers
- RPI:Weights (parts per 1000) Two-person pensioner - Gardening products
- RPI:Weights (parts per 1000) Two-person pensioner - Television licences and rent
- RPI:Weights (parts per 1000) Two-person pensioner - Entertainment & other recrea
- RPI:Weights (parts per 1000) Two-person pensioner - Food
- RPI:Weights (parts per 1000) Two-person pensioner - Catering
- RPI:Weights (parts per 1000) Two-person pensioner - Alcoholic drink
- RPI:Weights (parts per 1000) Two-person pensioner - Tobacco
- RPI:Weights (parts per 1000) Two-person pensioner - Fuel and light
- RPI:Weights (parts per 1000) Two-person pensioner - Household goods
- RPI:Weights (parts per 1000) Two-person pensioner - Household services
- RPI:Weights (parts per 1000) Two-person pensioner - Clothing and footwear
- RPI:Weights (parts per 1000) Two-person pensioner - Personal goods and services
- RPI:Weights (parts per 1000) Two-person pensioner - Motoring expenditure
- RPI:Weights (parts per 1000) Two-person pensioner - Fares and other travel costs
- RPI:Weights (parts per 1000) Two-person pensioner - Leisure goods
- RPI:Weights (parts per 1000) Two-person pensioner - Leisure services
- RPI: Percentage change over 12 months - Foreign holidays
- Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100
- RPI: Percentage change over 1 month - Food
- RPI All Items Excl Mortgage Interest (RPIX): Percentage change over 12 months
- Internal purchasing power of the pound (based on RPI): 1998=100
- Retail Prices Index: Long run series: annual percentage change
- RPI:Seasonally adjusted all items exc. MIPs and indirect taxes (SARPIY): Indices
- RPI: SA all items exc. MIPs and indirect taxes (SARPIY): % change over 12 months
- RPI: SA all items exc. MIPs and indirect taxes (SARPIY): % change over 1 month
- RPI All Items Index: Jan 1987=100
- RPI: All items exc. seasonal food (Jan 1987=100)
- RPI: All items exc. food (Jan 1987=100)
- RPI: All items exc. housing (Jan 1987=100)
- RPI: Total food (Jan 1987=100)
- RPI: Non-seasonal food (Jan 1987=100)
- RPI: Catering (Jan 1987=100)
- RPI: Alcoholic drink (Jan 1987=100)
- RPI: Cigarettes & tobacco (Jan 1987=100)
- RPI: Housing (Jan 1987=100)
- RPI: Fuel & light (Jan 1987=100)
- RPI: Household goods (Jan 1987=100)
- RPI: Household services (Jan 1987=100)
- RPI: Clothing & footwear (Jan 1987=100)
- RPI: Motoring expenditure (Jan 1987=100)
- RPI: Leisure goods (Jan 1987=100)
- RPI: Leisure services (Jan 1987=100)
- RPI: Seasonal food (Jan 1987=100)
- RPI: Personal goods & services (Jan 1987=100)
- RPI: Fares & other travel costs (Jan 1987=100)
- RPI: Food & catering (Jan 1987=100)
- RPI: Alcohol & tobacco (Jan 1987=100)
- RPI: Housing & household expenditure (Jan 1987=100)
- RPI: Personal expenditure (Jan 1987=100)
- RPI: Travel & leisure (Jan 1987=100)
- RPI: Consumer durables (Jan 1987=100)
- RPI All Items Index Excl Mortgage Interest (RPIX): Jan 1987=100
- RPI: Leisure services: foreign holidays (Jan 1993=100)
- RPI: Leisure services: UK Holidays (Jan 1994=100)
- RPI: All Goods (Jan 1987=100)
- RPI: All Services (Jan 1987=100)
- RPI: Utilities (Jan 1987=100)
- RPI: Shop Services (Jan 1987=100)
- RPI: Non-Shop Services (Jan 1987=100)
- RPI: Other Goods (Jan 1987=100)
- RPI : Petrol and Oil (including fuel oil) (Jan 1987=100)
- RPI: all items exc. mortgage interest payments and depreciation (Jan 1987=100)
- RPI: housing: depreciation(Jan 1995=100)
- CPI WEIGHTS 00 : HICP (Overall index)
- CPI WEIGHTS 01 : FOOD AND NON-ALCOHOLIC BEVERAGES
- CPI WEIGHTS 02 : ALCOHOLIC DRINKS, TOBACCO AND NARCOTICS
- CPI WEIGHTS 03 : CLOTHING AND FOOTWEAR
- CPI WEIGHTS 04 : HOUSING, WATER AND FUELS
- CPI WEIGHTS 05 : FURN, HH EQUIPMENT AND REPAIR OF THE HOUSE
- CPI WEIGHTS 06 : HEALTH
- CPI WEIGHTS 07 : TRANSPORT
- CPI WEIGHTS 08 : COMMUNICATION
- CPI WEIGHTS 09 : RECREATION & CULTURE
- CPI WEIGHTS 10 : EDUCATION
- CPI WEIGHTS 11 : HOTELS, CAFES AND RESTAURANTS
- CPI WEIGHTS 12 : MISCELLANEOUS GOODS AND SERVICES
- CPI WEIGHTS 01.1 : FOOD
- CPI WEIGHTS 01.2 : NON-ALCOHOLIC BEVERAGES
- CPI WEIGHTS 02.1 : ALCOHOLIC BEVERAGES
- CPI WEIGHTS 03.1 : CLOTHING
- CPI WEIGHTS 03.2 : FOOTWEAR INCLUDING REPAIRS
- CPI WEIGHTS 04.1 : ACTUAL RENTS FOR HOUSING
- CPI WEIGHTS 04.3 : REGULAR MAINTENANCE AND REPAIR OF THE DWELLING
- CPI WEIGHTS 04.4 : Water supply and misc. services for the dwelling
- CPI WEIGHTS 04.5 : ELECTRICITY, GAS AND OTHER FUELS
- CPI WEIGHTS 05.1 : Furniture, furnishings and carpets
- CPI WEIGHTS 05.2 : HOUSEHOLD TEXTILES
- CPI WEIGHTS 05.3 : MAJOR HOUSEHOLD APPLIANCES INCLUDING FITTINGS AND REPAIRS
- CPI WEIGHTS 05.4 : GLASSWARE, TABLEWARE AND HOUSEHOLD UTENSILS
- CPI WEIGHTS 05.5 : TOOLS AND EQUIPMENT FOR HOUSE AND GARDEN
- CPI WEIGHTS 05.6 : GOODS AND SERVICES FOR ROUTINE HOUSEHOLD MAINTENANCE
- CPI WEIGHTS 07.1 : PURCHASE OF VEHICLES
- CPI WEIGHTS 07.2 : OPERATION OF PERSONAL TRANSPORT EQUIPMENT
- CPI WEIGHTS 07.3 : TRANSPORT SERVICES
- CPI WEIGHTS 08.1 : POSTAL SERVICES
- CPI WEIGHTS 09.1 : Audio-visual equipment and related products
- CPI WEIGHTS 09.2 : OTHER MAJOR DURABLES FOR RECREATION AND CULTURE
- CPI WEIGHTS 09.3 : OTHER RECREATIONAL ITEMS AND EQUIPMENT GARDENS AND PETS
- CPI WEIGHTS 09.4 : RECREATIONAL AND CULTURAL SERVICES
- CPI WEIGHTS 11.1 : CATERING
- CPI WEIGHTS 11.2 : Accommodation services
- CPI WEIGHTS 12.1 : PERSONAL CARE
- CPI WEIGHTS 12.3 : PERSONAL EFFECTS N.E.C.
- CPI WEIGHTS 12.4 : SOCIAL PROTECTION
- CPI WEIGHTS 12.5 : INSURANCE

## 📌 Extract Specific CPI Column  
This cell selects and displays the CPI annual inflation series:  
**“CPI ANNUAL RATE 00: ALL ITEMS 2015=100”**  
The output helps confirm its values, structure, and suitability as the main inflation target for forecasting.

In [9]:
df_cpi["CPI ANNUAL RATE 00: ALL ITEMS 2015=100"].head(1000)
print(df_cpi["CPI ANNUAL RATE 00: ALL ITEMS 2015=100"].describe())

count     628
unique     96
top       2.4
freq       27
Name: CPI ANNUAL RATE 00: ALL ITEMS 2015=100, dtype: object

## 📌 View Date and CPI Annual Rate Columns  
This cell displays the first all rows of the CPI dataset, focusing on the `Title` column (date information) and the annual inflation series `CPI ANNUAL RATE 00: ALL ITEMS 2015=100`.

In [12]:
df_cpi[["Title", "CPI ANNUAL RATE 00: ALL ITEMS 2015=100"]].head(100000)

             Title CPI ANNUAL RATE 00: ALL ITEMS 2015=100
0             CDID                                   D7G7
1          PreUnit                                    NaN
2             Unit                                      %
3     Release Date                             22-10-2025
4     Next release                       19 November 2025
...            ...                                    ...
1476      2025 MAY                                    3.4
1477      2025 JUN                                    3.6
1478      2025 JUL                                    3.8
1479      2025 AUG                                    3.8
1480      2025 SEP                                    3.8

[1481 rows x 2 columns]

## 📊 Interest Rate Dataset Overview  
This cell reports the number of rows and columns in the interest rate dataset, prints the first ten records, and lists all column names in a column-wise format.  
It is used to inspect the structure of the Bank of England interest rate data before selecting the relevant series for analysis and merging.

In [4]:
# ============================================
# 📊 Interest Rate Data Overview (boe_interest.csv)
# ============================================

# Total rows and columns
print("Total rows:", df_interest.shape[0])
print("Total columns:", df_interest.shape[1])
print("=====================================\n")

# First 10 rows
print("First 10 rows:")
display(df_interest.head(10))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_interest.columns:
    print("-", col)

Total rows: 2526
Total columns: 2
=====================================

First 10 rows:

         Date  Bank Rate
0  27-11-2015        0.5
1  30-11-2015        0.5
2  01-12-2015        0.5
3  02-12-2015        0.5
4  03-12-2015        0.5
5  04-12-2015        0.5
6  07-12-2015        0.5
7  08-12-2015        0.5
8  09-12-2015        0.5
9  10-12-2015        0.5

=====================================

Column names:
- Date
- Bank Rate

## 📊 Exchange Rate Dataset Overview  
This cell displays the size of the exchange rate dataset, prints the first 100 rows, and lists all column names.  
It supports inspection of the dataset structure before selecting relevant variables for cleaning and merging.

In [6]:
# ============================================
# 📊 Exchange Rate Data Overview (exchange_rates.csv)
# ============================================

# Total rows and columns
print("Total rows:", df_exchange.shape[0])
print("Total columns:", df_exchange.shape[1])
print("=====================================\n")

# First 10 rows
print("First 10 rows:")
display(df_exchange.head(100))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_exchange.columns:
    print("-", col)

Total rows: 1161
Total columns: 2
=====================================

First 10 rows:

                Title Average Sterling exchange rate: US Dollar XUMAUSS
0                CDID                                              AUSS
1   Source dataset ID                                              MRET
2             PreUnit                                               NaN
3                Unit                                               NaN
4        Release date                                        16-10-2025
..                ...                                               ...
95            1947 Q1                                               NaN
96            1947 Q2                                               NaN
97            1947 Q3                                               NaN
98            1947 Q4                                               NaN
99            1948 Q1                                               NaN

[100 rows x 2 columns]

=====================================

Column names:
- Title
- Average Sterling exchange rate: US Dollar XUMAUSS

## 📊 GDP Growth Dataset Overview  
This cell displays the total number of rows and columns, prints the first ten observations, and lists all column names.  
It is used to examine the structure of the GDP growth dataset prior to cleaning and integration.

In [9]:
# ============================================
# 📊 GDP Growth Data Overview (GDP_growth_Rate.csv)
# ============================================

# Total rows and columns
print("Total rows:", df_gdp.shape[0])
print("Total columns:", df_gdp.shape[1])
print("=====================================\n")

# First 10 rows
print("First 100 rows:")
display(df_gdp.head(100))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_gdp.columns:
    print("-", col)

Total rows: 350
Total columns: 208
=====================================

First 100 rows:

,Title,Gross Value Added - Monthly (Index 1dp) :CVM SA,"Agriculture, Forestry and Fishing (Index 1dp) :CVM SA",Production Industries - Total (Index 1dp) :CVM SA,Mining and Quarrying (Index 1dp) :CVM SA,Manufacturing (Index 1dp) :CVM SA,"Electricity, gas, steam and air conditioning supply(Index 1dp) :CVM SA","Water supply; Sewerage,waste management & remediation activities (Index 1dp) :CVM SA",Construction (Index 1dp) :CVM SA,Service Industries - Total (Index 1dp) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (Index 1dp) :CVM SA,Transportation and Storage (Index 1dp) :CVM SA,Accommodation and food service activities (Index 1dp) :CVM SA,Information and communication (Index 1dp) :CVM SA,Financial and insurance activities (Index 1dp) :CVM SA,Real estate activities (Index 1dp) :CVM SA,"Professional, scientific and technical activities (Index 1dp) :CVM SA",Administrative and Support Service Activities (Index 1dp) :CVM SA,Public admin and defence; Compulsory social security (Index 1dp) :CVM SA,Education (Index 1dp) :CVM SA,Human health and social work activities (Index 1dp) :CVM SA,"Arts, Entertainment and Recreation (Index 1dp) :CVM SA",Other service activities (Index 1dp) :CVM SA,Activities of housholds as employers;Undiff goods & services (Index 1dp) :CVM SA,Gross Value Added - Monthly (period on period growth) :CVM SA,"Agriculture, Forestry and Fishing (period on period growth) :CVM SA",Production Industries - Total (period on period growth) :CVM SA,Mining and Quarrying (period on period growth) :CVM SA,Manufacturing (period on period growth) :CVM SA,"Electricity, gas, steam and air conditioning supply(period on period growth) :CVM SA","Water supply; Sewerage,waste management & remediation activities (period on period growth) :CVM SA",Construction (period on period growth) :CVM SA,Service Industries - Total (period on period growth) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (period on period growth) :CVM SA,Transportation and Storage (period on period growth) :CVM SA,Accommodation and food service activities (period on period growth) :CVM SA,Information and communication (period on period growth) :CVM SA,Financial and insurance activities (period on period growth) :CVM SA,Real estate activities (period on period growth) :CVM SA,"Professional, scientific and technical activities (period on period growth) :CVM SA",Administrative and Support Service Activities (period on period growth) :CVM SA,Public admin and defence; Compulsory social security (period on period growth) :CVM SA,Education (period on period growth) :CVM SA,Human health and social work activities (period on period growth) :CVM SA,"Arts, Entertainment and Recreation (period on period growth) :CVM SA",Other service activities (period on period growth) :CVM SA,Activities of housholds as employers;Undiff goods & services (period on period growth) :CVM SA,Gross Value Added - Monthly (period on period 1 year ago growth ) :CVM SA,"Agriculture, Forestry and Fishing (period on period 1 year ago growth) :CVM SA",Production Industries - Total (period on period 1 year ago growth) :CVM SA,Mining and Quarrying (period on period 1 year ago growth) :CVM SA,Manufacturing (period on period 1 year ago growth) :CVM SA,"Electricity, gas, steam and air conditioning supply(period on period 1 year ago growth) :CVM SA","Water supply; Sewerage,waste management & remediation activities (period on period 1 year ago growth) :CVM SA",Construction (period on period 1 year ago growth) :CVM SA,Service Industries - Total (period on period 1 year ago growth) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (period on period 1 year ago growth) :CVM SA,Transportation and Storage (period on period 1 year ago growth) :CVM SA,Accommodation and food service activities (period on period 1 year ago growth) :CVM SA,Information and communication (period on period 1 year ago growth) :CVM SA,Financial and insurance activities (period on period 1 year ago growth) :CVM SA,Real estate activities (period on period 1 year ago growth) :CVM SA,"Professional, scientific and technical activities (period on period 1 year ago growth) :CVM SA",Administrative and Support Service Activities (period on period 1 year ago growth) :CVM SA,Public admin and defence; Compulsory social security (period on period 1 year ago growth) :CVM SA,Education (period on period 1 year ago growth) :CVM SA,Human health and social work activities (period on period 1 year ago growth) :CVM SA,"Arts, Entertainment and Recreation (period on period 1 year ago growth) :CVM SA",Other service activities (period on period 1 year ago growth) :CVM SA,Activities of housholds as employers;Undiff goods & services (period on period 1 year ago growth) :CVM SA,Gross Value Added - Monthly (3 month on 3 month growth) :CVM SA,"Agriculture, Forestry and Fishing (3 month on 3 month growth) :CVM SA",Production Industries - Total (3 month on 3 month growth) :CVM SA,Mining and Quarrying (3 month on 3 month growth) :CVM SA,Manufacturing (3 month on 3 month growth) :CVM SA,"Electricity, gas, steam and air conditioning supply(3 month on 3 month growth) :CVM SA","Water supply; Sewerage,waste management & remediation activities (3 month on 3 month growth) :CVM SA",Construction (3 month on 3 month growth) :CVM SA,Service Industries - Total (3 month on 3 month growth) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (3 month on 3 month growth) :CVM SA,Transportation and Storage (3 month on 3 month growth) :CVM SA,Accommodation and food service activities (3 month on 3 month growth) :CVM SA,Information and communication (3 month on 3 month growth) :CVM SA,Financial and insurance activities (3 month on 3 month growth) :CVM SA,Real estate activities (3 month on 3 month growth) :CVM SA,"Professional, scientific and technical activities (3 month on 3 month growth) :CVM SA",Administrative and Support Service Activities (3 month on 3 month growth) :CVM SA,Public admin and defence; Compulsory social security (3 month on 3 month growth) :CVM SA,Education (3 month on 3 month growth) :CVM SA,Human health and social work activities (3 month on 3 month growth) :CVM SA,"Arts, Entertainment and Recreation (3 month on 3 month growth) :CVM SA",Other service activities (3 month on 3 month growth) :CVM SA,Activities of housholds as employers;Undiff goods & services (3 month on 3 month growth) :CVM SA,Gross Value Added - Monthly (3m on 3m 1 year ago growth) :CVM SA,"Agriculture, Forestry and Fishing (3m on 3m 1 year ago growth) :CVM SA",Production Industries - Total (3m on 3m 1 year ago growth) :CVM SA,Mining and Quarrying (3m on 3m 1 year ago growth) :CVM SA,Manufacturing (3m on 3m 1 year ago growth) :CVM SA,"Electricity, gas, steam and air conditioning supply(3m on 3m 1 year ago growth) :CVM SA","Water supply; Sewerage,waste management & remediation activities (3m on 3m 1 year ago growth) :CVM SA",Construction (3m on 3m 1 year ago growth) :CVM SA,Service Industries - Total (3m on 3m 1 year ago growth) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (3m on 3m 1 year ago growth) :CVM SA,Transportation and Storage (3m on 3m 1 year ago growth) :CVM SA,Accommodation and food service activities (3m on 3m 1 year ago growth) :CVM SA,Information and communication (3m on 3m 1 year ago growth) :CVM SA,Financial and insurance activities (3m on 3m 1 year ago growth) :CVM SA,Real estate activities (3m on 3m 1 year ago growth) :CVM SA,"Professional, scientific and technical activities (3m on 3m 1 year ago growth) :CVM SA",Administrative and Support Service Activities (3m on 3m 1 year ago growth) :CVM SA,Public admin and defence; Compulsory social security (3m on 3m 1 year ago growth) :CVM SA,Education (3m on 3m 1 year ago growth) :CVM SA,Human health and social work activities (3m on 3m 1 year ago growth) :CVM SA,"Arts, Entertainment and Recreation (3m on 3m 1 year ago growth) :CVM SA",Other service activities (3m on 3m 1 year ago growth) :CVM SA,Activities of housholds as employers;Undiff goods & services (3m on 3m 1 year ago growth) :CVM SA,Gross Value Added - Monthly (period on period contribution) :CVM SA,"Agriculture, Forestry and Fishing (period on period contribution) :CVM SA",Production Industries - Total (period on period contribution) :CVM SA,Mining and Quarrying (period on period contribution) :CVM SA,Manufacturing (period on period contribution) :CVM SA,"Electricity, gas, steam and air conditioning supply(period on period contribution) :CVM SA","Water supply; Sewerage,waste management & remediation activities (period on period contribution) :CVM SA",Construction (period on period contribution) :CVM SA,Service Industries - Total (period on period contribution) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (period on period contribution) :CVM SA,Transportation and Storage (period on period contribution) :CVM SA,Accommodation and food service activities (period on period contribution) :CVM SA,Information and communication (period on period contribution) :CVM SA,Financial and insurance activities (period on period contribution) :CVM SA,Real estate activities (period on period contribution) :CVM SA,"Professional, scientific and technical activities (period on period contribution) :CVM SA",Administrative and Support Service Activities (period on period contribution) :CVM SA,Public admin and defence; Compulsory social security (period on period contribution) :CVM SA,Education (period on period contribution) :CVM SA,Human health and social work activities (period on period contribution) :CVM SA,"Arts, Entertainment and Recreation (period on period contribution) :CVM SA",Other service activities (period on period contribution) :CVM SA,Activities of housholds as employers;Undiff goods & services (period on period contribution) :CVM SA,Gross Value Added - Monthly (period on period 1 year ago contribution ) :CVM SA,"Agriculture, Forestry and Fishing (period on period 1 year ago contribution ) :CVM SA",Production Industries - Total (period on period 1 year ago contribution ) :CVM SA,Mining and Quarrying (period on period 1 year ago contribution ) :CVM SA,Manufacturing (period on period 1 year ago contribution ) :CVM SA,"Electricity, gas, steam and air conditioning supply(period on period 1 year ago contribution ) :CVM SA","Water supply; Sewerage,waste management & remediation activities (period on period 1 year ago contribution ) :CVM SA",Construction (period on period 1 year ago contribution ) :CVM SA,Service Industries - Total (period on period 1 year ago contribution ) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (period on period 1 year ago contribution ) :CVM SA,Transportation and Storage (period on period 1 year ago contribution ) :CVM SA,Accommodation and food service activities (period on period 1 year ago contribution ) :CVM SA,Information and communication (period on period 1 year ago contribution ) :CVM SA,Financial and insurance activities (period on period 1 year ago contribution ) :CVM SA,Real estate activities (period on period 1 year ago contribution ) :CVM SA,"Professional, scientific and technical activities (period on period 1 year ago contribution ) :CVM SA",Administrative and Support Service Activities (period on period 1 year ago contribution ) :CVM SA,Public admin and defence; Compulsory social security (period on period 1 year ago contribution ) :CVM SA,Education (period on period 1 year ago contribution ) :CVM SA,Human health and social work activities (period on period 1 year ago contribution ) :CVM SA,"Arts, Entertainment and Recreation (period on period 1 year ago contribution ) :CVM SA",Other service activities (period on period 1 year ago contribution ) :CVM SA,Activities of housholds as employers;Undiff goods & services (period on period 1 year ago contribution ) :CVM SA,Gross Value Added - Monthly (3 month on 3 month contribution) :CVM SA,"Agriculture, Forestry and Fishing (3 month on 3 month contribution) :CVM SA",Production Industries - Total (3 month on 3 month contribution) :CVM SA,Mining and Quarrying (3 month on 3 month contribution) :CVM SA,Manufacturing (3 month on 3 month contribution) :CVM SA,"Electricity, gas, steam and air conditioning supply(3 month on 3 month contribution) :CVM SA","Water supply; Sewerage,waste management & remediation activities (3 month on 3 month contribution) :CVM SA",Construction (3 month on 3 month contribution) :CVM SA,Service Industries - Total (3 month on 3 month contribution) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (3 month on 3 month contribution) :CVM SA,Transportation and Storage (3 month on 3 month contribution) :CVM SA,Accommodation and food service activities (3 month on 3 month contribution) :CVM SA,Information and communication (3 month on 3 month contribution) :CVM SA,Financial and insurance activities (3 month on 3 month contribution) :CVM SA,Real estate activities (3 month on 3 month contribution) :CVM SA,"Professional, scientific and technical activities (3 month on 3 month contribution) :CVM SA",Administrative and Support Service Activities (3 month on 3 month contribution) :CVM SA,Public admin and defence; Compulsory social security (3 month on 3 month contribution) :CVM SA,Education (3 month on 3 month contribution) :CVM SA,Human health and social work activities (3 month on 3 month contribution) :CVM SA,"Arts, Entertainment and Recreation (3 month on 3 month contribution) :CVM SA",Other service activities (3 month on 3 month contribution) :CVM SA,Activities of housholds as employers;Undiff goods & services (3 month on 3 month contribution) :CVM SA,Gross Value Added - Monthly (3m on 3m 1 year ago contribution) :CVM SA,"Agriculture, Forestry and Fishing (3m on 3m 1 year ago contribution) :CVM SA",Production Industries - Total (3m on 3m 1 year ago contribution) :CVM SA,Mining and Quarrying (3m on 3m 1 year ago contribution) :CVM SA,Manufacturing (3m on 3m 1 year ago contribution) :CVM SA,"Electricity, gas, steam and air conditioning supply(3m on 3m 1 year ago contribution) :CVM SA","Water supply; Sewerage,waste management & remediation activities (3m on 3m 1 year ago contribution) :CVM SA",Construction (3m on 3m 1 year ago contribution) :CVM SA,Service Industries - Total (3m on 3m 1 year ago contribution) :CVM SA,Wholesale & retail trade; Repair of motor vehicles/cycles (3m on 3m 1 year ago contribution) :CVM SA,Transportation and Storage (3m on 3m 1 year ago contribution) :CVM SA,Accommodation and food service activities (3m on 3m 1 year ago contribution) :CVM SA,Information and communication (3m on 3m 1 year ago contribution) :CVM SA,Financial and insurance activities (3m on 3m 1 year ago contribution) :CVM SA,Real estate activities (3m on 3m 1 year ago contribution) :CVM SA,"Professional, scientific and technical activities (3m on 3m 1 year ago contribution) :CVM SA",Administrative and Support Service Activities (3m on 3m 1 year ago contribution) :CVM SA,Public admin and defence; Compulsory social security (3m on 3m 1 year ago contribution) :CVM SA,Education (3m on 3m 1 year ago contribution) :CVM SA,Human health and social work activities (3m on 3m 1 year ago contribution) :CVM SA,"Arts, Entertainment and Recreation (3m on 3m 1 year ago contribution) :CVM SA",Other service activities (3m on 3m 1 year ago contribution) :CVM SA,Activities of housholds as employers;Undiff goods & services (3m on 3m 1 year ago contribution) :CVM SA
0,CDID,ECY2,ECY3,ECY4,ECY5,ECY6,ECY7,ECY8,ECY9,ECYC,ECYD,ECYG,ECYH,ECYI,ECYJ,ECYK,ECYL,ECYP,ECYQ,ECYR,ECYS,ECYT,ECYU,ECYV,ECYX,ECYY,ECYZ,ECZ2,ECZA,ECZC,ECZD,ECZE,ECZG,ECZK,ECZN,ECZT,ECZU,ED2G,ED2H,ED2I,ED2J,ED2K,ED2L,ED2M,ED2N,ED2O,ED2P,ED2R,ED2S,ED2T,ED2U,ED2V,ED2W,ED2X,ED2Y,ED2Z,ED32,ED33,ED34,ED35,ED36,ED37,ED38,ED39,ED3A,ED3B,ED3C,ED3D,ED3E,ED3F,ED3H,ED3I,ED3J,ED3K,ED3L,ED3M,ED3N,ED3O,ED3P,ED3Q,ED3R,ED3S,ED3T,ED3U,ED3V,ED3W,ED3X,ED3Y,ED3Z,ED42,ED43,ED44,ED9R,ED9T,ED9U,ED9V,ED9W,EDGQ,EDGR,EDGS,EDGT,EDGU,EDGV,EDGW,EDGX,EDGY,EDGZ,EDHA,EDHB,EDHC,EDHD,EDHE,EDHF,EDHG,EDHH,EDHI,EDKH,EDKI,EDKJ,EDKK,EDKL,EDKM,EDKN,EDKO,EDKP,EDKQ,EDKR,EDKS,EDKT,EDKU,EDKV,EDKW,EDKX,EDKY,EDKZ,EDLA,EDLB,EDLC,EDLD,EDLE,EDLF,EDLG,EDLH,EDLI,EDLJ,EDLK,EDLL,EDLM,EDLN,EDLO,EDLP,EDLQ,EDLR,EDLS,EDLT,EDLU,EDLV,EDLW,EDLX,EDLY,EDLZ,EDMA,EDMB,EDMC,EDMD,EDME,EDMF,EDMG,EDMH,EDMI,EDMJ,EDMK,EDML,EDMM,EDMN,EDMO,EDMP,EDMQ,EDMR,EDMS,EDMT,EDMU,EDMV,EDMW,EDMX,EDMY,EDMZ,EDNA,EDNB,EDNC,EDND,EDNE,EDNF,EDNG,EDNH,EDNI,EDNJ,EDNK,EDNL,EDNM,EDNN,EDNO,EDNP,EDNQ,EDNR,EDNS,EDNT,EDNU
1,PreUnit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Unit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

=====================================

Column names:
- Title
- Gross Value Added - Monthly (Index 1dp) :CVM SA
- Agriculture, Forestry and Fishing (Index 1dp) :CVM SA
- Production Industries - Total (Index 1dp) :CVM SA
- Mining and Quarrying (Index 1dp) :CVM SA
- Manufacturing (Index 1dp) :CVM SA
- Electricity, gas, steam and air conditioning supply(Index 1dp) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (Index 1dp) :CVM SA
- Construction (Index 1dp) :CVM SA
- Service Industries - Total (Index 1dp) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (Index 1dp) :CVM SA
- Transportation and Storage (Index 1dp) :CVM SA
- Accommodation and food service activities (Index 1dp) :CVM SA
- Information and communication (Index 1dp) :CVM SA
- Financial and insurance activities (Index 1dp) :CVM SA
- Real estate activities (Index 1dp) :CVM SA
- Professional, scientific and technical activities (Index 1dp) :CVM SA
- Administrative and Support Service Activities (Index 1dp) :CVM SA
- Public admin and defence; Compulsory social security (Index 1dp) :CVM SA
- Education (Index 1dp) :CVM SA
- Human health and social work activities (Index 1dp) :CVM SA
- Arts, Entertainment and Recreation (Index 1dp) :CVM SA
- Other service activities (Index 1dp) :CVM SA
- Activities of housholds as employers;Undiff goods & services (Index 1dp) :CVM SA
- Gross Value Added - Monthly (period on period growth) :CVM SA
- Agriculture, Forestry and Fishing (period on period growth) :CVM SA
- Production Industries - Total (period on period growth) :CVM SA
- Mining and Quarrying (period on period growth) :CVM SA
- Manufacturing (period on period growth) :CVM SA
- Electricity, gas, steam and air conditioning supply(period on period growth) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (period on period growth) :CVM SA
- Construction (period on period growth) :CVM SA
- Service Industries - Total (period on period growth) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (period on period growth) :CVM SA
- Transportation and Storage (period on period growth) :CVM SA
- Accommodation and food service activities (period on period growth) :CVM SA
- Information and communication (period on period growth) :CVM SA
- Financial and insurance activities (period on period growth) :CVM SA
- Real estate activities (period on period growth) :CVM SA
- Professional, scientific and technical activities (period on period growth) :CVM SA
- Administrative and Support Service Activities (period on period growth) :CVM SA
- Public admin and defence; Compulsory social security (period on period growth) :CVM SA
- Education (period on period growth) :CVM SA
- Human health and social work activities (period on period growth) :CVM SA
- Arts, Entertainment and Recreation (period on period growth) :CVM SA
- Other service activities (period on period growth) :CVM SA
- Activities of housholds as employers;Undiff goods & services (period on period growth) :CVM SA
- Gross Value Added - Monthly (period on period 1 year ago growth ) :CVM SA
- Agriculture, Forestry and Fishing (period on period 1 year ago growth) :CVM SA
- Production Industries - Total (period on period 1 year ago growth) :CVM SA
- Mining and Quarrying (period on period 1 year ago growth) :CVM SA
- Manufacturing (period on period 1 year ago growth) :CVM SA
- Electricity, gas, steam and air conditioning supply(period on period 1 year ago growth) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (period on period 1 year ago growth) :CVM SA
- Construction (period on period 1 year ago growth) :CVM SA
- Service Industries - Total (period on period 1 year ago growth) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (period on period 1 year ago growth) :CVM SA
- Transportation and Storage (period on period 1 year ago growth) :CVM SA
- Accommodation and food service activities (period on period 1 year ago growth) :CVM SA
- Information and communication (period on period 1 year ago growth) :CVM SA
- Financial and insurance activities (period on period 1 year ago growth) :CVM SA
- Real estate activities (period on period 1 year ago growth) :CVM SA
- Professional, scientific and technical activities (period on period 1 year ago growth) :CVM SA
- Administrative and Support Service Activities (period on period 1 year ago growth) :CVM SA
- Public admin and defence; Compulsory social security (period on period 1 year ago growth) :CVM SA
- Education (period on period 1 year ago growth) :CVM SA
- Human health and social work activities (period on period 1 year ago growth) :CVM SA
- Arts, Entertainment and Recreation (period on period 1 year ago growth) :CVM SA
- Other service activities (period on period 1 year ago growth) :CVM SA
- Activities of housholds as employers;Undiff goods & services (period on period 1 year ago growth) :CVM SA
- Gross Value Added - Monthly (3 month on 3 month growth) :CVM SA
- Agriculture, Forestry and Fishing (3 month on 3 month growth) :CVM SA
- Production Industries - Total (3 month on 3 month growth) :CVM SA
- Mining and Quarrying (3 month on 3 month growth) :CVM SA
- Manufacturing (3 month on 3 month growth) :CVM SA
- Electricity, gas, steam and air conditioning supply(3 month on 3 month growth) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (3 month on 3 month growth) :CVM SA
- Construction (3 month on 3 month growth) :CVM SA
- Service Industries - Total (3 month on 3 month growth) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (3 month on 3 month growth) :CVM SA
- Transportation and Storage (3 month on 3 month growth) :CVM SA
- Accommodation and food service activities (3 month on 3 month growth) :CVM SA
- Information and communication (3 month on 3 month growth) :CVM SA
- Financial and insurance activities (3 month on 3 month growth) :CVM SA
- Real estate activities (3 month on 3 month growth) :CVM SA
- Professional, scientific and technical activities (3 month on 3 month growth) :CVM SA
- Administrative and Support Service Activities (3 month on 3 month growth) :CVM SA
- Public admin and defence; Compulsory social security (3 month on 3 month growth) :CVM SA
- Education (3 month on 3 month growth) :CVM SA
- Human health and social work activities (3 month on 3 month growth) :CVM SA
- Arts, Entertainment and Recreation (3 month on 3 month growth) :CVM SA
- Other service activities (3 month on 3 month growth) :CVM SA
- Activities of housholds as employers;Undiff goods & services (3 month on 3 month growth) :CVM SA
- Gross Value Added - Monthly (3m on 3m 1 year ago growth) :CVM SA
- Agriculture, Forestry and Fishing (3m on 3m 1 year ago growth) :CVM SA
- Production Industries - Total (3m on 3m 1 year ago growth) :CVM SA
- Mining and Quarrying (3m on 3m 1 year ago growth) :CVM SA
- Manufacturing (3m on 3m 1 year ago growth) :CVM SA
- Electricity, gas, steam and air conditioning supply(3m on 3m 1 year ago growth) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (3m on 3m 1 year ago growth) :CVM SA
- Construction (3m on 3m 1 year ago growth) :CVM SA
- Service Industries - Total (3m on 3m 1 year ago growth) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (3m on 3m 1 year ago growth) :CVM SA
- Transportation and Storage (3m on 3m 1 year ago growth) :CVM SA
- Accommodation and food service activities (3m on 3m 1 year ago growth) :CVM SA
- Information and communication (3m on 3m 1 year ago growth) :CVM SA
- Financial and insurance activities (3m on 3m 1 year ago growth) :CVM SA
- Real estate activities (3m on 3m 1 year ago growth) :CVM SA
- Professional, scientific and technical activities (3m on 3m 1 year ago growth) :CVM SA
- Administrative and Support Service Activities (3m on 3m 1 year ago growth) :CVM SA
- Public admin and defence; Compulsory social security (3m on 3m 1 year ago growth) :CVM SA
- Education (3m on 3m 1 year ago growth) :CVM SA
- Human health and social work activities (3m on 3m 1 year ago growth) :CVM SA
- Arts, Entertainment and Recreation (3m on 3m 1 year ago growth) :CVM SA
- Other service activities (3m on 3m 1 year ago growth) :CVM SA
- Activities of housholds as employers;Undiff goods & services (3m on 3m 1 year ago growth) :CVM SA
- Gross Value Added - Monthly (period on period contribution) :CVM SA
- Agriculture, Forestry and Fishing (period on period contribution) :CVM SA
- Production Industries - Total (period on period contribution) :CVM SA
- Mining and Quarrying (period on period contribution) :CVM SA
- Manufacturing (period on period contribution) :CVM SA
- Electricity, gas, steam and air conditioning supply(period on period contribution) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (period on period contribution) :CVM SA
- Construction (period on period contribution) :CVM SA
- Service Industries - Total (period on period contribution) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (period on period contribution) :CVM SA
- Transportation and Storage (period on period contribution) :CVM SA
- Accommodation and food service activities (period on period contribution) :CVM SA
- Information and communication (period on period contribution) :CVM SA
- Financial and insurance activities (period on period contribution) :CVM SA
- Real estate activities (period on period contribution) :CVM SA
- Professional, scientific and technical activities (period on period contribution) :CVM SA
- Administrative and Support Service Activities (period on period contribution) :CVM SA
- Public admin and defence; Compulsory social security (period on period contribution) :CVM SA
- Education (period on period contribution) :CVM SA
- Human health and social work activities (period on period contribution) :CVM SA
- Arts, Entertainment and Recreation (period on period contribution) :CVM SA
- Other service activities (period on period contribution) :CVM SA
- Activities of housholds as employers;Undiff goods & services (period on period contribution) :CVM SA
- Gross Value Added - Monthly (period on period 1 year ago contribution ) :CVM SA
- Agriculture, Forestry and Fishing (period on period 1 year ago contribution ) :CVM SA
- Production Industries - Total (period on period 1 year ago contribution ) :CVM SA
- Mining and Quarrying (period on period 1 year ago contribution ) :CVM SA
- Manufacturing (period on period 1 year ago contribution ) :CVM SA
- Electricity, gas, steam and air conditioning supply(period on period 1 year ago contribution ) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (period on period 1 year ago contribution ) :CVM SA
- Construction (period on period 1 year ago contribution ) :CVM SA
- Service Industries - Total (period on period 1 year ago contribution ) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (period on period 1 year ago contribution ) :CVM SA
- Transportation and Storage (period on period 1 year ago contribution ) :CVM SA
- Accommodation and food service activities (period on period 1 year ago contribution ) :CVM SA
- Information and communication (period on period 1 year ago contribution ) :CVM SA
- Financial and insurance activities (period on period 1 year ago contribution ) :CVM SA
- Real estate activities (period on period 1 year ago contribution ) :CVM SA
- Professional, scientific and technical activities (period on period 1 year ago contribution ) :CVM SA
- Administrative and Support Service Activities (period on period 1 year ago contribution ) :CVM SA
- Public admin and defence; Compulsory social security (period on period 1 year ago contribution ) :CVM SA
- Education (period on period 1 year ago contribution ) :CVM SA
- Human health and social work activities (period on period 1 year ago contribution ) :CVM SA
- Arts, Entertainment and Recreation (period on period 1 year ago contribution ) :CVM SA
- Other service activities (period on period 1 year ago contribution ) :CVM SA
- Activities of housholds as employers;Undiff goods & services (period on period 1 year ago contribution ) :CVM SA
- Gross Value Added - Monthly (3 month on 3 month contribution) :CVM SA
- Agriculture, Forestry and Fishing (3 month on 3 month contribution) :CVM SA
- Production Industries - Total (3 month on 3 month contribution) :CVM SA
- Mining and Quarrying (3 month on 3 month contribution) :CVM SA
- Manufacturing (3 month on 3 month contribution) :CVM SA
- Electricity, gas, steam and air conditioning supply(3 month on 3 month contribution) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (3 month on 3 month contribution) :CVM SA
- Construction (3 month on 3 month contribution) :CVM SA
- Service Industries - Total (3 month on 3 month contribution) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (3 month on 3 month contribution) :CVM SA
- Transportation and Storage (3 month on 3 month contribution) :CVM SA
- Accommodation and food service activities (3 month on 3 month contribution) :CVM SA
- Information and communication (3 month on 3 month contribution) :CVM SA
- Financial and insurance activities (3 month on 3 month contribution) :CVM SA
- Real estate activities (3 month on 3 month contribution) :CVM SA
- Professional, scientific and technical activities (3 month on 3 month contribution) :CVM SA
- Administrative and Support Service Activities (3 month on 3 month contribution) :CVM SA
- Public admin and defence; Compulsory social security (3 month on 3 month contribution) :CVM SA
- Education (3 month on 3 month contribution) :CVM SA
- Human health and social work activities (3 month on 3 month contribution) :CVM SA
- Arts, Entertainment and Recreation (3 month on 3 month contribution) :CVM SA
- Other service activities (3 month on 3 month contribution) :CVM SA
- Activities of housholds as employers;Undiff goods & services (3 month on 3 month contribution) :CVM SA
- Gross Value Added - Monthly (3m on 3m 1 year ago contribution) :CVM SA
- Agriculture, Forestry and Fishing (3m on 3m 1 year ago contribution) :CVM SA
- Production Industries - Total (3m on 3m 1 year ago contribution) :CVM SA
- Mining and Quarrying (3m on 3m 1 year ago contribution) :CVM SA
- Manufacturing (3m on 3m 1 year ago contribution) :CVM SA
- Electricity, gas, steam and air conditioning supply(3m on 3m 1 year ago contribution) :CVM SA
- Water supply; Sewerage,waste management & remediation activities (3m on 3m 1 year ago contribution) :CVM SA
- Construction (3m on 3m 1 year ago contribution) :CVM SA
- Service Industries - Total (3m on 3m 1 year ago contribution) :CVM SA
- Wholesale & retail trade; Repair of motor vehicles/cycles (3m on 3m 1 year ago contribution) :CVM SA
- Transportation and Storage (3m on 3m 1 year ago contribution) :CVM SA
- Accommodation and food service activities (3m on 3m 1 year ago contribution) :CVM SA
- Information and communication (3m on 3m 1 year ago contribution) :CVM SA
- Financial and insurance activities (3m on 3m 1 year ago contribution) :CVM SA
- Real estate activities (3m on 3m 1 year ago contribution) :CVM SA
- Professional, scientific and technical activities (3m on 3m 1 year ago contribution) :CVM SA
- Administrative and Support Service Activities (3m on 3m 1 year ago contribution) :CVM SA
- Public admin and defence; Compulsory social security (3m on 3m 1 year ago contribution) :CVM SA
- Education (3m on 3m 1 year ago contribution) :CVM SA
- Human health and social work activities (3m on 3m 1 year ago contribution) :CVM SA
- Arts, Entertainment and Recreation (3m on 3m 1 year ago contribution) :CVM SA
- Other service activities (3m on 3m 1 year ago contribution) :CVM SA
- Activities of housholds as employers;Undiff goods & services (3m on 3m 1 year ago contribution) :CVM SA

## 📌 Selected GDP Columns  
This cell extracts and displays the four key GDP growth series:  
- Monthly index  
- Period-on-period growth  
- Three-month-on-three-month growth  
- Three-month-on-three-month growth compared with one year ago  
The all observations are shown for inspection.

In [14]:
selected_cols = [
    "Title",
    "Gross Value Added - Monthly (Index 1dp) :CVM SA",
    "Gross Value Added - Monthly (period on period growth) :CVM SA",
    "Gross Value Added - Monthly (3 month on 3 month growth) :CVM SA",
    "Gross Value Added - Monthly (3m on 3m 1 year ago growth) :CVM SA"
]

df_gdp[selected_cols].head(1000)

            Title Gross Value Added - Monthly (Index 1dp) :CVM SA Gross Value Added - Monthly (period on period growth) :CVM SA Gross Value Added - Monthly (3 month on 3 month growth) :CVM SA Gross Value Added - Monthly (3m on 3m 1 year ago growth) :CVM SA
0            CDID                                            ECY2                                               ECYX                                                          ED3H                                                            ED9T
1         PreUnit                                             NaN                                                NaN                                                           NaN                                                             NaN
2            Unit                                             NaN                                                NaN                                                           NaN                                                             NaN
3    Release Date                                      16-10-2025                                         16-10-2025                                                    16-10-2025                                                      16-10-2025
4    Next release                                13 November 2025                                   13 November 2025                                              13 November 2025                                                13 November 2025
..            ...                                             ...                                                ...                                                           ...                                                             ...
345      2025 APR                                           102.3                                               -0.2                                                           0.7                                                             1.6
346      2025 MAY                                           102.4                                                0.0                                                           0.5                                                             1.4
347      2025 JUN                                           102.7                                                0.4                                                           0.3                                                             1.3
348      2025 JUL                                           102.6                                               -0.1                                                           0.2                                                             1.4
349      2025 AUG                                           102.7                                                0.1                                                           0.3                                                             1.5

[350 rows x 5 columns]

In [12]:


print("Selected GDP column names:")
for col in selected_cols:
    print("-", col)

Selected GDP column names:
- Gross Value Added - Monthly (Index 1dp) :CVM SA
- Gross Value Added - Monthly (period on period growth) :CVM SA
- Gross Value Added - Monthly (3 month on 3 month growth) :CVM SA
- Gross Value Added - Monthly (3m on 3m 1 year ago growth) :CVM SA

## 📊 Unemployment Dataset Overview  
This cell shows the number of rows and columns, prints the first ten records, and lists the unemployment dataset's column names to support variable inspection and selection.

In [15]:
# ============================================
# 📊 Unemployment Data Overview (Unemployment_Rate.csv)
# ============================================

# Total rows and columns
print("Total rows:", df_unemp.shape[0])
print("Total columns:", df_unemp.shape[1])
print("=====================================\n")

# First 10 rows
print("First 10 rows:")
display(df_unemp.head(10))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_unemp.columns:
    print("-", col)

Total rows: 933
Total columns: 2
=====================================

First 10 rows:

               Title Unemployment rate (aged 16 and over, seasonally adjusted): %
0               CDID                                               MGSX
1  Source dataset ID                                                LMS
2            PreUnit                                                NaN
3               Unit                                                  %
4       Release date                                         14-10-2025
5       Next release                                   11 November 2025
6    Important notes                                                NaN
7               1971                                                4.1
8               1972                                                4.3
9               1973                                                3.7

=====================================

Column names:
- Title
- Unemployment rate (aged 16 and over, seasonally adjusted): %

## 📊 Oil Price Dataset Overview  
This cell reports the total number of rows and columns in the oil price dataset, displays the first ten observations, and lists each column name to support variable inspection and later selection.

In [16]:
# ============================================
# 📊 Oil Price Data Overview (petrol_oil_everage_price_change.csv)
# ============================================

# Total rows and columns
print("Total rows:", df_oil.shape[0])
print("Total columns:", df_oil.shape[1])
print("=====================================\n")

# First 10 rows
print("First 10 rows:")
display(df_oil.head(10))
print("=====================================\n")

# Column names (one per line)
print("Column names:")
for col in df_oil.columns:
    print("-", col)

Total rows: 649
Total columns: 2
=====================================

First 10 rows:

               Title RPI: Percentage change over 12 months - Petrol and Oil incl Fuel Oil
0               CDID                                               DOGQ
1  Source dataset ID                                               MM23
2            PreUnit                                                NaN
3               Unit                                                  %
4       Release date                                         19-11-2025
5       Next release                                   17 December 2025
6    Important notes                                                NaN
7               1988                                               -1.7
8               1989                                                7.2
9               1990                                               12.7

=====================================

Column names:
- Title
- RPI: Percentage change over 12 months - Petrol and Oil incl Fuel Oil